version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crm
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: sh -c "npx prisma migrate deploy && node dist/index.js"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/crm?schema=public
      PORT: 4000
      JWT_SECRET: dev-secret
      JWT_EXPIRES_IN: 1d
    depends_on:
      - db
    ports:
      - "4000:4000"

  frontend:
    build: .
    command: sh -c "npm run build && npm run start"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:4000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:


